name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Check if index.html changed
      - name: Check if index.html changed
        id: check_changes
        run: |
          # Use git diff to check for changes in index.html
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'index.html' && echo "true" || echo "false" > changed.txt

      # Read file with changed flag
      - name: Read file with changed flag
        id: read_flag
        run: |
          # Read the contents of the changed.txt file
          CHANGED=$(<changed.txt)
          # Set the output variable 'changed' with the value
          echo "::set-output name=changed::$CHANGED"

      # Run workflow if index.html changed
      - name: Run workflow if index.html changed
        if: steps.read_flag.outputs.changed == 'true'
        run: |
          # Add your workflow steps here
          echo Hello, world!
